-- Szövegértés-bank: fázison túli betűket tartalmazó rossz válaszok cseréje
-- Részletek/áttekintés: comprehension_fix_review.md (77 elem)
-- Futtasd le a Supabase SQL Editorban, majd publikálj az admin felületről!

UPDATE comprehension_bank SET wrong_answers = ARRAY['sós', 'mai'] WHERE id = 'c33';
UPDATE comprehension_bank SET wrong_answers = ARRAY['vet', 'etet'] WHERE id = 'c93';
UPDATE comprehension_bank SET wrong_answers = ARRAY['les', 'etet'] WHERE id = 'c94';
UPDATE comprehension_bank SET wrong_answers = ARRAY['siet', 'vet'] WHERE id = 'c95';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sima', 'lila'] WHERE id = 'c96';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sima', 'lila'] WHERE id = 'c97';
UPDATE comprehension_bank SET wrong_answers = ARRAY['tapsol', 'mos'] WHERE id = 'c100';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sós', 'sima'] WHERE id = 'c101';
UPDATE comprehension_bank SET wrong_answers = ARRAY['siet', 'olvas'] WHERE id = 'c34';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a villamos', 'a tó'] WHERE id = 'c98';
UPDATE comprehension_bank SET wrong_answers = ARRAY['lassú', 'sima'] WHERE id = 'c99';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a malac', 'a sas'] WHERE id = 'c102';
UPDATE comprehension_bank SET wrong_answers = ARRAY['olvas', 'tapsol'] WHERE id = 'c103';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a posta', 'a palota'] WHERE id = 'c104';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a pipa', 'a posta'] WHERE id = 'c105';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a sapka', 'a kuka'] WHERE id = 'c106';
UPDATE comprehension_bank SET wrong_answers = ARRAY['etet', 'mos'] WHERE id = 'c107';
UPDATE comprehension_bank SET wrong_answers = ARRAY['okos', 'lusta'] WHERE id = 'c73';
UPDATE comprehension_bank SET wrong_answers = ARRAY['pakol', 'mos'] WHERE id = 'c74';
UPDATE comprehension_bank SET wrong_answers = ARRAY['itat', 'olvas'] WHERE id = 'c109';
UPDATE comprehension_bank SET wrong_answers = ARRAY['lapos', 'sima'] WHERE id = 'c75';
UPDATE comprehension_bank SET wrong_answers = ARRAY['lusta', 'okos'] WHERE id = 'c76';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a síp', 'a kefe'] WHERE id = 'c110';
UPDATE comprehension_bank SET wrong_answers = ARRAY['olvas', 'vasal'] WHERE id = 'c111';
UPDATE comprehension_bank SET wrong_answers = ARRAY['festett', 'lapos'] WHERE id = 'c77';
UPDATE comprehension_bank SET wrong_answers = ARRAY['olvas', 'fest'] WHERE id = 'c78';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sima', 'sós'] WHERE id = 'c112';
UPDATE comprehension_bank SET wrong_answers = ARRAY['álmos', 'lusta'] WHERE id = 'c113';
UPDATE comprehension_bank SET wrong_answers = ARRAY['áll', 'lapul'] WHERE id = 'c114';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sima', 'lila'] WHERE id = 'c80';
UPDATE comprehension_bank SET wrong_answers = ARRAY['vizes', 'lila'] WHERE id = 'c115';
UPDATE comprehension_bank SET wrong_answers = ARRAY['vasal', 'olvas'] WHERE id = 'c116';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sós', 'sima'] WHERE id = 'c81';
UPDATE comprehension_bank SET wrong_answers = ARRAY['zamatos', 'lila'] WHERE id = 'c82';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a tó', 'az út'] WHERE id = 'c118';
UPDATE comprehension_bank SET wrong_answers = ARRAY['mos', 'vasal'] WHERE id = 'c83';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a hó', 'az alma'] WHERE id = 'c84';
UPDATE comprehension_bank SET wrong_answers = ARRAY['az út', 'a ház'] WHERE id = 'c119';
UPDATE comprehension_bank SET wrong_answers = ARRAY['fekete', 'lila'] WHERE id = 'c120';
UPDATE comprehension_bank SET wrong_answers = ARRAY['álmos', 'lassú'] WHERE id = 'c85';
UPDATE comprehension_bank SET wrong_answers = ARRAY['fest', 'fut'] WHERE id = 'c86';
UPDATE comprehension_bank SET wrong_answers = ARRAY['festett', 'zöld'] WHERE id = 'c121';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a mókus', 'a teve'] WHERE id = 'c122';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sós', 'illatos'] WHERE id = 'c87';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sós', 'vizes'] WHERE id = 'c88';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a kés', 'a tál'] WHERE id = 'c123';
UPDATE comprehension_bank SET wrong_answers = ARRAY['fut', 'dalol'] WHERE id = 'c124';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sós', 'vizes'] WHERE id = 'c89';
UPDATE comprehension_bank SET wrong_answers = ARRAY['vizes', 'sós'] WHERE id = 'c90';
UPDATE comprehension_bank SET wrong_answers = ARRAY['int', 'dalol'] WHERE id = 'c125';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a ló', 'a tehén'] WHERE id = 'c126';
UPDATE comprehension_bank SET wrong_answers = ARRAY['nevet', 'fut'] WHERE id = 'c127';
UPDATE comprehension_bank SET wrong_answers = ARRAY['lapos', 'festett'] WHERE id = 'c35';
UPDATE comprehension_bank SET wrong_answers = ARRAY['széles', 'sima'] WHERE id = 'c129';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sós', 'zamatos'] WHERE id = 'c130';
UPDATE comprehension_bank SET wrong_answers = ARRAY['levest', 'diót'] WHERE id = 'c37';
UPDATE comprehension_bank SET wrong_answers = ARRAY['hideg', 'sós'] WHERE id = 'c131';
UPDATE comprehension_bank SET wrong_answers = ARRAY['áll', 'dolgozik'] WHERE id = 'c132';
UPDATE comprehension_bank SET wrong_answers = ARRAY['vastag', 'zöld'] WHERE id = 'c133';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a réten', 'a földön'] WHERE id = 'c42';
UPDATE comprehension_bank SET wrong_answers = ARRAY['érdes és sárga', 'rövid és piros'] WHERE id = 'c43';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a réten', 'a tetőn'] WHERE id = 'c44';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a parton', 'az úton'] WHERE id = 'c51';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a réten', 'a földön'] WHERE id = 'c53';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sós', 'érdes és zöld'] WHERE id = 'c7';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a földön', 'a réten'] WHERE id = 'c11';
UPDATE comprehension_bank SET wrong_answers = ARRAY['fehér', 'fekete'] WHERE id = 'c134';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a földön', 'a széken'] WHERE id = 'c41';
UPDATE comprehension_bank SET wrong_answers = ARRAY['autóval', 'kockával'] WHERE id = 'c14';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a mama', 'a néni'] WHERE id = 'c3';
UPDATE comprehension_bank SET wrong_answers = ARRAY['sós és éretlen', 'keserű és száraz'] WHERE id = 'c48';
UPDATE comprehension_bank SET wrong_answers = ARRAY['álmos és lusta', 'félős és lusta'] WHERE id = 'c55';
UPDATE comprehension_bank SET wrong_answers = ARRAY['pici és fehér', 'sárga és szürke'] WHERE id = 'c39';
UPDATE comprehension_bank SET wrong_answers = ARRAY['meleg és sós', 'forró és keserű'] WHERE id = 'c56';
UPDATE comprehension_bank SET wrong_answers = ARRAY['rövid és új', 'nagyon rövid'] WHERE id = 'c70';
UPDATE comprehension_bank SET sentence = 'A kiscsirke puha és sárga.', correct_answer = 'puha és sárga', wrong_answers = ARRAY['nagy és fekete', 'érdes és fehér'] WHERE id = 'c25';
UPDATE comprehension_bank SET wrong_answers = ARRAY['a patakban', 'az égen'] WHERE id = 'c67';
